cells: [
  'L23_PC_cADpyr229_1_passdends',
  'L23_PC_cADpyr229_3_passdends',
  'L5_TTPC1_cADpyr232_1.py',
  'L5_TTPC2_cADpyr232_1.py'
]

# controls light power of MultiStimulator in mW
norm_power: [
  0.0001,
  0.0004,
  0.0016,
  0.0064,
  0.0256,
  0.1024,
  0.4096,
]

# light source setup:
slp_diameter_um : 200
slp_NA : 0.22

# space scanned with light source
xy_max : 500
dxy : 50
