cell_ids: [
  'L23_PC_cADpyr229_1',
]

# controls light power of MultiStimulator in mW
norm_power: [
  0.0002,
]
cond_scale_fct: [0.85]

# light source setup:
slp_diameter_um : 50
slp_NA : 0.1

# space scanned with light source
xymax : 110
dxy : 10

# cluster grid width
cluster_grid_width : [50]
