cells: [
  'L23_PC_cADpyr229_1_passdends',
]
# controls light power of MultiStimulator in mW
norm_power: [
  0.01,
  #  0.02,
  0.04,
  #  0.08,
  0.16,
  #  0.32,
  0.64,
  #  1.28,
  2.56,
  #  5.12,
  10.24,
  #  20.48,
  40.96,
  #  81.92
]
lp_config: ['config0', 'config1', 'config2']
pattern_iterations: 100
cond_scl_fct: [1.0]
