cells: [
  'L23_PC_cADpyr229_1_passdends',
  'L23_PC_cADpyr229_2_passdends',
  'L23_PC_cADpyr229_3_passdends',
  'L23_PC_cADpyr229_4_passdends',
]
rel_intensities: [1, 3, 6, 10, 15, 20, 30, 45, 60, 100, 140, 180]
lp_config: ['config0', 'config1', 'config2']
cond_scale_factors: [1.0]
pattern_iterations: 100
target_n_locs: ['9999'] # '9999' means all comps are recorded.
